apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka
  namespace: openfaas
spec:
  serviceName: kafka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:4.0.0
        ports:
        - containerPort: 9092
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-bwater-data-vol
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-service:9092
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_CLEANUP_POLICY
          value: compact
        - name: KAFKA_NUM_PARTITIONS
          value: "1"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_RESERVED_BROKER_MAX_ID
          value: "999999999"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181
      volumes:
        - name: kafka-bwater-data-vol
          persistentVolumeClaim:
            claimName: bwater-kafka-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: openfaas
spec:
  ports:
  - port: 9092
  selector:
    app: kafka
