apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka1
  namespace: openfaas
spec:
  serviceName: kafka1-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka1
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka1
        image: confluentinc/cp-kafka:4.0.0
        ports:
        - containerPort: 9092
        volumeMounts:
        - mountPath: /var/lib/kafka
          name: kafka1-bwater-data-vol
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka1
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka1-service:9092
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_CLEANUP_POLICY
          value: compact
        - name: KAFKA_NUM_PARTITIONS
          value: "10"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_RESERVED_BROKER_MAX_ID
          value: "999999999"
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      volumes:
        - name: kafka1-bwater-data-vol
          persistentVolumeClaim:
            claimName: bwater-kafka1-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: kafka1-service
  namespace: openfaas
spec:
  ports:
  - port: 9092
  selector:
    app: kafka1
    
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka2
  namespace: openfaas
spec:
  serviceName: kafka2-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka2
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka2
        image: confluentinc/cp-kafka:4.0.0
        ports:
        - containerPort: 9092
        volumeMounts:
        - mountPath: /var/lib/kafka
          name: kafka2-bwater-data-vol
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka2
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka2-service:9092
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_CLEANUP_POLICY
          value: compact
        - name: KAFKA_NUM_PARTITIONS
          value: "10"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_BROKER_ID
          value: "2"
        - name: KAFKA_RESERVED_BROKER_MAX_ID
          value: "999999999"
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      volumes:
        - name: kafka2-bwater-data-vol
          persistentVolumeClaim:
            claimName: bwater-kafka2-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: kafka2-service
  namespace: openfaas
spec:
  ports:
  - port: 9092
  selector:
    app: kafka2

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: kafka3
  namespace: openfaas
spec:
  serviceName: kafka3-service
  replicas: 1
  template:
    metadata:
      labels:
        app: kafka3
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: kafka3
        image: confluentinc/cp-kafka:4.0.0
        ports:
        - containerPort: 9092
        volumeMounts:
        - mountPath: /var/lib/kafka
          name: kafka3-bwater-data-vol
        env:
        - name: KAFKA_ADVERTISED_HOST_NAME
          value: kafka3
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka3-service:9092
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_LOG_CLEANUP_POLICY
          value: compact
        - name: KAFKA_NUM_PARTITIONS
          value: "10"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_BROKER_ID
          value: "3"
        - name: KAFKA_RESERVED_BROKER_MAX_ID
          value: "999999999"
        - name: KAFKA_LOG_DIRS
          value: /var/lib/kafka/data
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper1:2181,zookeeper2:2181,zookeeper3:2181"
      volumes:
        - name: kafka3-bwater-data-vol
          persistentVolumeClaim:
            claimName: bwater-kafka3-volume-claim
---
apiVersion: v1
kind: Service
metadata:
  name: kafka3-service
  namespace: openfaas
spec:
  ports:
  - port: 9092
  selector:
    app: kafka3
